name: tabr
channels:
- https://conda.anaconda.org/nvidia
- https://conda.anaconda.org/conda-forge
- nodefaults
dependencies:
- catboost=1.1.1
# - faiss-gpu=1.7.2
- faiss-cpu=1.7.2
- gpytorch=1.9.1
- jupyterlab=3.6.1
- loguru=0.6.0
- numpy=1.24.2
- optuna=3.1.0
- pandas=1.5.3
- pytorch::pytorch=1.13.1
# - pytorch::pytorch-cuda=11.7
- pytorch::pytorch-mutex=1.0
- scipy=1.10.1
- tensorboard=2.12.0
- tomli=2.0.1
- tomli-w=1.0.0
- tqdm=4.65.0
- pip:
  - delu==0.0.15
  - einops==0.6.1
  - rtdl==0.0.13
  - xgboost==1.7.4
